# Generated by Django 2.0.3 on 2021-03-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(default='0', max_length=30, verbose_name='Telefon'),
        ),
    ]
