# Generated by Django 2.0.3 on 2021-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employee_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.CharField(default='0', max_length=30, verbose_name='Kullanıcı Tipi'),
        ),
    ]
