# Generated by Django 2.0.3 on 2021-03-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_employee_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, default='0', max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(blank=True, default='0', max_length=30, verbose_name='Kullanıcı Tipi'),
        ),
    ]
