# Generated by Django 2.0.3 on 2021-03-06 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20210304_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('aciklama', models.CharField(max_length=100, verbose_name='Açıklama')),
                ('kategori', models.CharField(default='default', max_length=15, verbose_name='Kategori')),
                ('workflow', models.IntegerField(default=1, verbose_name='Workflow ID')),
                ('workflow_status', models.CharField(default='10', max_length=3, verbose_name='work flow status')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='beceri',
            field=models.CharField(blank=True, choices=[('ADOKAPI', 'ADOKAPI'), ('PARKE', 'PARKE'), ('ÇELİKKAPI', 'ÇELİKKAPI'), ('YANGIN KAPISI', 'YANGIN KAPISI'), ('MONTAJCI', 'MONTAJCI'), ('MARANGOZ', 'MARANGOZ')], default='0', max_length=30, verbose_name='Kullanıcı Tipi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='sube',
            field=models.CharField(blank=True, choices=[('Fethiye', 'Fethiye'), ('Muğla', 'Muğla'), ('Bodrum', 'Bodrum'), ('Marmaris', 'Marmaris'), ('Antalya', 'Antalya')], default='0', max_length=30, verbose_name='Kullanıcı Tipi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Yönetici'), ('2', 'Satış'), ('3', 'Taşeron')], default='0', max_length=30, verbose_name='Kullanıcı Tipi'),
        ),
    ]
