# Generated by Django 2.0.3 on 2021-03-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210306_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('10000', 'Finans'), ('20000', 'Mali ve İdari işler'), ('30000', 'Satış'), ('31000', 'Saha Görevlisi'), ('40000', 'Operasyon'), ('41000', 'Planlama')], max_length=100),
        ),
    ]
