# Generated by Django 2.0.3 on 2021-03-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210307_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='beceri',
            field=models.CharField(blank=True, choices=[('ADOKAPI', 'ADOKAPI'), ('PARKE', 'PARKE'), ('ÇELİKKAPI', 'ÇELİKKAPI'), ('YANGIN KAPISI', 'YANGIN KAPISI'), ('MONTAJCI', 'MONTAJCI'), ('MARANGOZ', 'MARANGOZ')], default='0', max_length=30, verbose_name='Beceri'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sube',
            field=models.CharField(blank=True, choices=[('Fethiye', 'Fethiye'), ('Muğla', 'Muğla'), ('Bodrum', 'Bodrum'), ('Marmaris', 'Marmaris'), ('Antalya', 'Antalya')], default='0', max_length=30, verbose_name='Şube'),
        ),
    ]
