# Generated by Django 2.0.3 on 2021-03-10 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210310_0458'),
        ('user', '0007_auto_20210307_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
