# Generated by Django 2.0.3 on 2021-03-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_logging_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logging',
            name='user',
        ),
        migrations.AddField(
            model_name='logging',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Employee'),
        ),
    ]
