# Generated by Django 2.0.3 on 2021-03-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210310_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logging',
            name='employee',
        ),
    ]
