# Generated by Django 2.0.3 on 2021-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_logging_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='user',
            field=models.IntegerField(default=1, verbose_name='User ID'),
        ),
    ]
