# Generated by Django 2.0.3 on 2021-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_logging_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='user',
            field=models.CharField(default='1', max_length=15, verbose_name='User ID'),
        ),
    ]
