# Generated by Django 2.0.3 on 2021-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210310_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order ID'),
        ),
    ]
