# Generated by Django 2.0.3 on 2021-03-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210310_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='workflow_status',
            field=models.CharField(blank=True, default='10', max_length=3, verbose_name='work flow status'),
        ),
    ]
