# Generated by Django 2.0.3 on 2021-03-11 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210310_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logging',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='logging',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='logging',
            name='workflow_status',
        ),
        migrations.AddField(
            model_name='logging',
            name='log_type',
            field=models.CharField(default='genel', max_length=20, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='logging',
            name='status',
            field=models.CharField(blank=True, default='10', max_length=3, null=True, verbose_name='work flow status'),
        ),
        migrations.AddField(
            model_name='logging',
            name='type_id',
            field=models.IntegerField(default=1, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='logging',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
