# Generated by Django 2.0.3 on 2021-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210311_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='status',
            field=models.CharField(blank=True, default='10', max_length=3, null=True, verbose_name='Status'),
        ),
    ]
