# Generated by Django 2.0.3 on 2021-03-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210311_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logging',
            name='order',
        ),
    ]
