# Generated by Django 2.0.3 on 2021-03-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_logging_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_number', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
