# Generated by Django 2.0.3 on 2021-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210408_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_type',
        ),
    ]
