# Generated by Django 2.0.3 on 2021-04-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210408_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Sube'),
        ),
    ]
