# Generated by Django 2.0.3 on 2021-04-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210408_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yetenek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='beceri',
        ),
        migrations.AddField(
            model_name='employee',
            name='yetenek',
            field=models.ManyToManyField(to='user.Yetenek'),
        ),
    ]
