# Generated by Django 2.0.3 on 2021-04-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210408_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='yetenek',
            field=models.ManyToManyField(null=True, to='user.Yetenek'),
        ),
    ]
