# Generated by Django 2.0.3 on 2021-04-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20210408_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='yetenek',
            field=models.ManyToManyField(to='user.Yetenek'),
        ),
    ]
