# Generated by Django 2.0.3 on 2021-04-09 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0025_auto_20210408_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yetki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yetkilendirme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('satis_gir', 'Saış girişi için gerekli yetki'), ('müsteri_gir', 'Müşteri tanımlama'), ('kullanici_yonetim', 'Kullanıcı yönetimi')),
            },
        ),
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.Departments', verbose_name='Departman'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
