# Generated by Django 2.0.3 on 2021-04-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20210411_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='user.Departments', verbose_name='Departman'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, default='Kullanıcı', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sube',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='user.Sube', verbose_name='Şube'),
        ),
    ]
