# Generated by Django 2.0.3 on 2021-05-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20210416_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yetkilendirme',
            options={'permissions': (('siparis_yonetimi', 'Satış girişi için gerekli yetki'), ('siparis_listele', 'Satışları listeleme'), ('urun_listele', 'Ürün Listeleme'), ('urun_yonetim', 'Ürün ekleme,güncelleme,deaktif etme'), ('musteri_listele', 'Müşteri listeleme'), ('musteri_yonetim', 'Müşteri ekleme,güncelleme,silme'), ('kullanici_listeleme', 'Kullanıcı listeleme'), ('kullanici_yonetim', 'Kullanıcı yönetimi'), ('rezervasyon_listele', 'Rezervasyonları listeleme görüntüleme'), ('rezervasyon_yonetim', 'Rezervasyon yönetim işlemleri'), ('rapor_listele', 'Rapor listeleme'), ('log_listeleme', 'Logları görme'), ('musterisikayet_listeleme', 'Müşteri şikayetleri listele gör'), ('musterisikayet_yonetim', 'Müşteri şikayetleri yönetimi'), ('workflow_operasyon', 'Workflow Operasyon '), ('workflow_planlama', 'Workflow Planlama  '), ('workflow_depo', 'Workflow Depo '), ('workflow_uretim', 'Workflow Uretim '), ('test', 'test yetkisi'))},
        ),
    ]
