# Generated by Django 2.0.3 on 2021-03-02 08:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='MÜŞTERİ ADI')),
                ('telephone', models.CharField(max_length=50, verbose_name='TELEFON')),
                ('email', models.CharField(max_length=254, verbose_name='EMAIL')),
                ('adress', models.CharField(max_length=50, verbose_name='FİRMA ADRESİ')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('order_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Sipariş Formunu Ekleyiniz')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer', verbose_name='Müşteri ID')),
            ],
        ),
    ]
