# Generated by Django 2.0.3 on 2021-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.CharField(blank=True, max_length=50, verbose_name='FİRMA ADRESİ'),
        ),
    ]
