# Generated by Django 2.0.3 on 2021-03-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210303_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='U', max_length=1, verbose_name='Sipariş tipi'),
        ),
    ]
