# Generated by Django 2.0.3 on 2021-03-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210304_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('U', 'Üretim'), ('S', 'Sevk'), ('M', 'Montaj')], max_length=1, verbose_name='Sipariş tipi'),
        ),
    ]
