# Generated by Django 2.0.3 on 2021-03-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210304_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('U', 'U'), ('S', 'S'), ('M', 'M')], max_length=1, verbose_name='Sipariş tipi'),
        ),
    ]
