# Generated by Django 2.0.3 on 2021-03-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210304_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statu',
            field=models.CharField(choices=[('0', 'Beklemede'), ('10', 'Uretim Planlandı'), ('11', 'Uretimde'), ('12', 'Uretildi'), ('20', 'Sevk Alanında'), ('21', 'Sevk Edildi'), ('30', 'Montaj Müşteriden haber bekleniyor'), ('31', 'Takvimlendirildi'), ('39', 'Sorun var'), ('99', 'Tamamlandı')], default='0', max_length=2, verbose_name='Sipariş Durumu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('U', 'U'), ('S', 'S'), ('M', 'M')], max_length=1, verbose_name='Sipariş Tipi'),
        ),
    ]
