# Generated by Django 2.0.3 on 2021-03-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210304_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, verbose_name='Order ID')),
                ('department', models.CharField(choices=[('10000', 'Finans'), ('20000', 'Mali ve İdari işler'), ('30000', 'Satış'), ('31000', 'Saha Görevlisi'), ('40000', 'Operasyon'), ('41000', 'Planlama')], max_length=10, verbose_name='Order ID')),
                ('revision', models.IntegerField(max_length=2, verbose_name='Revizyon')),
                ('approve_user_id', models.IntegerField(max_length=6, verbose_name='İşi onaylayan kullanıcı')),
                ('completed_user_id', models.IntegerField(max_length=6, verbose_name='İşi yapan Kullanıcı')),
                ('wf_status', models.CharField(choices=[('10', 'Beklemede'), ('20', 'Çalışılıyor'), ('30', 'İptal edildi'), ('40', 'Tamamlandı')], max_length=10, verbose_name='Durum')),
                ('created_date', models.DateField(auto_now=True)),
                ('planed_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
