# Generated by Django 2.0.3 on 2021-03-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='wf_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='order_id',
        ),
        migrations.AddField(
            model_name='workflow',
            name='order',
            field=models.ManyToManyField(to='order.Order'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='approve_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='İşi onaylayan kullanıcı'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='completed_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='İşi yapan Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='revision',
            field=models.IntegerField(default=1, verbose_name='Revizyon'),
        ),
    ]
