# Generated by Django 2.0.3 on 2021-03-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210306_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='department',
            field=models.CharField(choices=[('10000', 'Finans'), ('20000', 'Mali ve İdari işler'), ('30000', 'Satış'), ('31000', 'Saha Görevlisi'), ('40000', 'Operasyon'), ('41000', 'Planlama')], max_length=10, verbose_name='Departman'),
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='order',
        ),
        migrations.AddField(
            model_name='workflow',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
