# Generated by Django 2.0.3 on 2021-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210306_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='comment',
            field=models.CharField(default='test', max_length=50, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('10', 'Beklemede'), ('20', 'Çalışılıyor'), ('30', 'İptal edildi'), ('40', 'Tamamlandı')], default='10', max_length=10, verbose_name='Durum'),
        ),
    ]
