# Generated by Django 2.0.3 on 2021-03-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210306_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun', models.CharField(max_length=20, verbose_name='Ürün adı')),
                ('kisaltma', models.CharField(max_length=5, verbose_name='Kısa ad(kod)')),
                ('montaj_sabiti', models.IntegerField(verbose_name='Montaj Sabiti')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('active', models.CharField(default='1', max_length=1, verbose_name='Aktif')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.CharField(default='1', max_length=1, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='planed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
