# Generated by Django 2.0.3 on 2021-03-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210306_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('U', 'Uretim'), ('S', 'Sevk'), ('M', 'Montaj')], max_length=1, verbose_name='Sipariş Tipi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='statu',
            field=models.CharField(choices=[('00', 'Beklemede'), ('10', 'Uretim Planlandı'), ('11', 'Uretimde'), ('12', 'Uretildi'), ('20', 'Sevk Alanında'), ('21', 'Sevk Edildi'), ('30', 'Montaj Müşteriden haber bekleniyor'), ('31', 'Takvimlendirildi'), ('39', 'Sorun var'), ('90', 'Tamamlandı')], default='0', max_length=2, verbose_name='Sipariş Durumu'),
        ),
    ]
