# Generated by Django 2.0.3 on 2021-03-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210306_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stok',
            field=models.CharField(choices=[('U', 'Uretim'), ('S', 'Sevk'), ('M', 'Montaj')], default=0, max_length=1, verbose_name='Sipariş Tipi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('1', 'Var'), ('0', 'Yok')], default='0', max_length=1, verbose_name='Stok Durumu'),
        ),
    ]
