# Generated by Django 2.0.3 on 2021-03-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210309_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('U', 'Uretim'), ('S', 'Sevk'), ('M', 'Montaj'), ('D', 'Depo Teslim')], max_length=1, verbose_name='Sipariş Tipi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='statu',
            field=models.CharField(choices=[('00', 'Beklemede'), ('10', 'Uretim planı bekleniyor'), ('12', 'Uretim planlandı'), ('14', 'Uretimde'), ('16', 'Uretim tamamlandı'), ('20', 'Sevk planı bekleniyor'), ('22', 'Sevk planlandı'), ('24', 'Sevk alanında'), ('26', 'Sevk edildi'), ('28', 'Sevk teslim edildi'), ('30', 'Montaj planı bekleniyor'), ('31', 'Takvimlendirildi'), ('32', 'Montaj Müşteriden haber bekleniyor'), ('34', 'Montaj planlandı'), ('40', 'Montaj operasyonu bekleniyor.'), ('42', 'Montaj başlandı'), ('44', 'Montaj durdu '), ('46', 'Montaj tamamlandı '), ('50', 'Depo teslim alma için müşteriyi bekliyor '), ('52', 'Depo müşteriye teslim etti '), ('80', 'Sorun var'), ('90', 'Tamamlandı')], default='0', max_length=2, verbose_name='Sipariş Durumu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stok',
            field=models.CharField(choices=[('1', 'Var'), ('0', 'Yok')], default='0', max_length=1, verbose_name='Stok Durumu'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='department',
            field=models.CharField(choices=[('10000', 'Finans'), ('20000', 'Mali ve İdari işler'), ('30000', 'Satış'), ('31000', 'Saha Görevlisi'), ('40000', 'Operasyon'), ('41000', 'Planlama'), ('42000', 'Üretim'), ('43000', 'Depo'), ('44000', 'Montaj')], max_length=10, verbose_name='Departman'),
        ),
    ]
