# Generated by Django 2.0.3 on 2021-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210310_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cinsi',
            field=models.CharField(default=1, help_text='xxx gibi bilgiler', max_length=15, verbose_name='Cinsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.CharField(default=234, max_length=15, verbose_name='Marka'),
            preserve_default=False,
        ),
    ]
