# Generated by Django 2.0.3 on 2021-03-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210312_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulke', models.CharField(max_length=30, verbose_name='ULKE')),
                ('il', models.CharField(max_length=30, verbose_name='IL')),
                ('ilce', models.CharField(max_length=30, verbose_name='İLÇE')),
                ('adres', models.CharField(max_length=100, verbose_name='ADRES')),
                ('map_link', models.CharField(max_length=100, verbose_name='GOOGLE MAP')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer', verbose_name='Müşteri ID')),
            ],
        ),
    ]
