# Generated by Django 2.0.3 on 2021-03-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ulke',
            field=models.CharField(default='Türkiye', max_length=30, verbose_name='ULKE'),
        ),
    ]
