# Generated by Django 2.0.3 on 2021-03-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_customer_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='urun',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cinsi',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kisaltma',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Kısa ad(kod)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Adet', max_length=10, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
