# Generated by Django 2.0.3 on 2021-03-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_orderproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='colour',
            field=models.CharField(blank=True, max_length=20, verbose_name='Renk'),
        ),
    ]
