# Generated by Django 2.0.3 on 2021-03-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_orderproducts_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
