# Generated by Django 2.0.3 on 2021-03-17 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0023_address_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True)),
                ('closed_date', models.DateField(blank=True)),
                ('description', models.CharField(blank=True, max_length=40, verbose_name='Açıklama')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Durum')),
            ],
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Durum')),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.AddField(
            model_name='problems',
            name='root_cause',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.RootCause'),
        ),
        migrations.AddField(
            model_name='problems',
            name='statu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ProblemStatu'),
        ),
    ]
