# Generated by Django 2.0.3 on 2021-03-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20210318_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='root_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.RootCause'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='statu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.ProblemStatu'),
        ),
    ]
