# Generated by Django 2.0.3 on 2021-03-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20210318_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Employee'),
        ),
    ]
