# Generated by Django 2.0.3 on 2021-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20210318_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
