# Generated by Django 2.0.3 on 2021-03-18 10:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20210318_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='solution',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
