# Generated by Django 2.0.3 on 2021-03-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20210320_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Durum Numarası')),
                ('title', models.CharField(max_length=20, verbose_name='kategori')),
            ],
        ),
    ]
