# Generated by Django 2.0.3 on 2021-03-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_orderstatu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatu',
            name='title',
            field=models.CharField(max_length=50, verbose_name='kategori'),
        ),
    ]
