# Generated by Django 2.0.3 on 2021-03-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_auto_20210320_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statu',
            field=models.CharField(choices=[('00', 'Beklemede'), ('10', 'Uretim planı bekleniyor'), ('12', 'Uretim planlandı'), ('14', 'Uretimde'), ('16', 'Uretim tamamlandı'), ('20', 'Sevk planı bekleniyor'), ('22', 'Sevk planlandı'), ('24', 'Sevk alanında'), ('26', 'Sevk edildi'), ('28', 'Sevk teslim edildi'), ('30', 'Montaj planı bekleniyor'), ('32', 'Takvimlendirildi'), ('34', 'Montaj Müşteriden haber bekleniyor'), ('36', 'Montaj planlandı'), ('40', 'Montaj operasyonu bekleniyor.'), ('42', 'Montaj başlandı'), ('44', 'Montaj durdu '), ('46', 'Montaj tamamlandı '), ('50', 'Depo teslim alma için müşteriyi bekliyor '), ('52', 'Depo müşteriye teslim etti '), ('80', 'Sorun var'), ('90', 'Tamamlandı')], default='0', max_length=2, verbose_name='Sipariş Durumu'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.OrderStatu'),
        ),
    ]
