# Generated by Django 2.0.3 on 2021-03-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_auto_20210320_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.OrderStatu'),
        ),
    ]
