# Generated by Django 2.0.3 on 2021-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20210320_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatu',
            name='aciklama',
            field=models.CharField(max_length=50, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='orderstatu',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Order Statu'),
        ),
    ]
