# Generated by Django 2.0.3 on 2021-03-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_departments'),
        ('order', '0034_auto_20210320_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationperson',
            name='user',
        ),
        migrations.AddField(
            model_name='reservationperson',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Employee'),
            preserve_default=False,
        ),
    ]
