# Generated by Django 2.0.3 on 2021-03-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20210323_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='fisNo',
            field=models.IntegerField(default=1, null=True, verbose_name='Fiş NO'),
        ),
        migrations.AlterField(
            model_name='order',
            name='statu',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.PROTECT, to='order.OrderStatu'),
        ),
    ]
