# Generated by Django 2.0.3 on 2021-03-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_auto_20210326_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vergi_no',
            field=models.IntegerField(default=0, null=True, verbose_name='Vergi/TC no'),
        ),
    ]
