# Generated by Django 2.0.3 on 2021-04-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_customer_vergi_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Şahıs', 'Şahıs'), ('Kurumsal', 'Kurumsal')], default='Şahıs', max_length=10, verbose_name='Şahıs/Kurumsal'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vergi_dairesi',
            field=models.CharField(default='Fethiye VD.', max_length=70, verbose_name='Vergi Dairesi'),
        ),
    ]
