# Generated by Django 2.0.3 on 2021-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20210403_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='birim_fiyat',
            field=models.IntegerField(default=0, verbose_name='Birim Fiyat'),
        ),
    ]
