# Generated by Django 2.0.3 on 2021-04-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_product_birim_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='iskonto',
            field=models.IntegerField(default=0, verbose_name='İskonto Oranı(%)'),
        ),
    ]
