# Generated by Django 2.0.3 on 2021-04-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_order_iskonto'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tahmini_tarih_max',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tahmini_tarih_min',
            field=models.DateField(null=True),
        ),
    ]
