# Generated by Django 2.0.3 on 2021-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_auto_20210405_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='birim_fiyat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='toplam_tutar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tahmini_tarih_max',
            field=models.DateField(null=True, verbose_name='En geç teslim (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tahmini_tarih_min',
            field=models.DateField(null=True, verbose_name='En erken teslim (yyyy-mm-dd)'),
        ),
    ]
