# Generated by Django 2.0.3 on 2021-04-13 07:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20210405_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='aciklama',
            field=models.CharField(default=1, max_length=10, verbose_name='Açıklama(kısa/kod)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer', verbose_name='Müşteri'),
        ),
    ]
