# Generated by Django 2.0.3 on 2021-04-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_order_sevk_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sevk_adres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.Address', verbose_name='Sevk Adresi'),
        ),
    ]
