# Generated by Django 2.0.3 on 2021-04-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20210413_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='satis_kanali',
            field=models.CharField(choices=[('Perakende', 'Perakende'), ('Toptan', 'Toptan'), ('Proje', 'Proje')], default=1, max_length=10, verbose_name='Satış Kanalı'),
            preserve_default=False,
        ),
    ]
