# Generated by Django 2.0.3 on 2021-04-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_order_satis_kanali'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.ProductCategory', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='main_category',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
