# Generated by Django 2.0.3 on 2021-04-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_auto_20210417_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UrunGrubu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Marka', verbose_name='Urun Grubu'),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_grubu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.UrunGrubu', verbose_name='Urun Grubu'),
        ),
    ]
