# Generated by Django 2.0.3 on 2021-04-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_auto_20210420_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.ProductCategory', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='urun tipi', help_text='xxx gibi bilgiler', max_length=15, verbose_name='Cinsi'),
        ),
    ]
