# Generated by Django 2.0.3 on 2021-04-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_auto_20210420_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='planlama_sekli',
            field=models.CharField(choices=[('En Hızlı', 'En Hızlı'), ('Müşteriden Haber Bekle', 'Müşteriden Haber Bekle'), ('Müsaitliğimize Göre', 'Müsaitliğimize Göre')], default='En Hızlı', max_length=20, verbose_name='Planlama Şekli'),
        ),
    ]
