# Generated by Django 2.0.3 on 2021-04-21 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_order_planlama_sekli'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='urun_grubu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.UrunGrubu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='planlama_sekli',
            field=models.CharField(choices=[('En Hızlı', 'En Hızlı'), ('Müş.den Haber Bekle', 'Müş.den Haber Bekle'), ('Müsaitliğimize Göre', 'Müsaitliğimize Göre')], default='En Hızlı', max_length=20, verbose_name='Planlama Şekli'),
        ),
    ]
