# Generated by Django 2.0.3 on 2021-04-21 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_auto_20210421_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='urun_grubu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.UrunGrubu'),
            preserve_default=False,
        ),
    ]
