# Generated by Django 2.0.3 on 2021-04-27 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_problems_urun_grubu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='urungrubu',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='urun_kodu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ürün Kodu'),
        ),
        migrations.AlterField(
            model_name='marka',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='montaj_sabiti',
            field=models.IntegerField(default=0, verbose_name='Montaj Sabiti'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='Ürün adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.ProductType', verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('AD', 'AD'), ('TN', 'TN'), ('M2', 'M2'), ('PK', 'PK'), ('TK', 'TK'), ('MT', 'MT'), ('BY', 'BY'), ('M3', 'M3'), ('KG', 'KG')], default='AD', max_length=10, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='urungrubu',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
