# Generated by Django 2.0.3 on 2021-04-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_auto_20210427_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Ürün adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kodu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ürün Kodu'),
        ),
    ]
