# Generated by Django 2.0.3 on 2021-05-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_auto_20210427_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mahalle',
            field=models.CharField(default=1, max_length=30, verbose_name='MAHALLE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ölçü/Üretim Dökümanı'),
        ),
    ]
