# Generated by Django 2.0.3 on 2021-05-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20210521_0247'),
        ('order', '0056_auto_20210504_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sube',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.Sube', verbose_name='Şube'),
            preserve_default=False,
        ),
    ]
