# Generated by Django 2.0.3 on 2021-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0057_order_sube'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fatura_adres',
            field=models.IntegerField(null=True, verbose_name='Fatura Adresi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sevk_adres',
            field=models.IntegerField(null=True, verbose_name='Sevk Adresi'),
        ),
    ]
