# Generated by Django 2.0.3 on 2021-05-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0058_auto_20210522_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPackets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('U', 'Uretim'), ('S', 'Sevk'), ('M', 'Montaj'), ('D', 'Depo Teslim')], max_length=1, verbose_name='Sipariş Tipi')),
                ('status', models.BooleanField(default=False)),
                ('order_product', models.ManyToManyField(to='order.OrderProducts')),
            ],
        ),
    ]
