# Generated by Django 2.0.3 on 2021-05-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_orderpackets'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpackets',
            name='order_id',
            field=models.IntegerField(default=1, verbose_name='order id'),
            preserve_default=False,
        ),
    ]
