# Generated by Django 2.0.3 on 2021-06-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_orderpackets_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpackets',
            name='order_id',
        ),
    ]
