# Generated by Django 2.0.3 on 2021-06-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0061_remove_orderpackets_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpackets',
            name='order_id',
            field=models.IntegerField(default=1, verbose_name='order id'),
            preserve_default=False,
        ),
    ]
