# Generated by Django 2.0.3 on 2021-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_orderpackets_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpackets',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='orderpackets_id',
            field=models.IntegerField(default=0),
        ),
    ]
