# Generated by Django 2.0.3 on 2021-06-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0063_auto_20210603_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpackets',
            name='order_product',
        ),
    ]
