# Generated by Django 2.0.3 on 2021-06-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_remove_orderpackets_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='orderpackets_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.OrderPackets'),
        ),
    ]
