# Generated by Django 2.0.3 on 2021-06-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_auto_20210603_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='orderpackets_id',
            new_name='orderpackets',
        ),
    ]
