# Generated by Django 2.0.3 on 2021-06-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0066_auto_20210603_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='siparis_paketi',
            field=models.BooleanField(default=False, verbose_name='siparis paketi'),
        ),
    ]
