# Generated by Django 2.0.3 on 2021-06-03 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_order_siparis_paketi'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='siparis_paketi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.OrderPackets'),
        ),
    ]
