# Generated by Django 2.0.3 on 2021-06-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_workflow_siparis_paketi'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpackets',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
