# Generated by Django 2.0.3 on 2021-06-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_orderpackets_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renk_kodu', models.CharField(blank=True, max_length=20, verbose_name='Renk')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.ProductCategory', verbose_name='Kategori')),
            ],
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ProductColor'),
        ),
    ]
