# Generated by Django 2.0.3 on 2021-06-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_auto_20210613_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
