# Generated by Django 2.0.3 on 2021-06-22 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_remove_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpackets',
            name='uretim',
            field=models.BooleanField(default=False, verbose_name='Üretim var/yok'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ProductColor', verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Product', verbose_name='Ürün'),
        ),
    ]
