# Generated by Django 2.0.3 on 2021-06-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_auto_20210622_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpackets',
            name='order_id',
        ),
    ]
