# Generated by Django 2.0.3 on 2021-06-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0073_remove_orderpackets_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Miktar'),
        ),
    ]
