# Generated by Django 2.0.3 on 2021-07-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0075_reservation_order_packet'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Workflow'),
            preserve_default=False,
        ),
    ]
