# Generated by Django 2.0.3 on 2021-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_reservation_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='urun_grubu',
        ),
        migrations.AddField(
            model_name='problems',
            name='problem_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Problem dosya/resim'),
        ),
    ]
