# Generated by Django 2.0.3 on 2021-07-12 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_auto_20210712_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
