# Generated by Django 2.0.3 on 2021-07-16 17:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0078_auto_20210712_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
