# Generated by Django 2.0.3 on 2021-07-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0079_auto_20210716_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='satis_kanali',
        ),
    ]
