# Generated by Django 2.0.3 on 2021-07-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0080_auto_20210716_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='satis_kanali',
            field=models.CharField(choices=[('Perakende', 'Perakende'), ('Toptan', 'Toptan'), ('Proje', 'Proje')], default='Perakende', max_length=10, verbose_name='Satış Kanalı'),
        ),
    ]
