# Generated by Django 2.0.3 on 2021-07-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0081_customer_satis_kanali'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_wf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='wf_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='siparis_paketi',
            field=models.BooleanField(default=False, verbose_name='siparis paketi statu'),
        ),
    ]
