# Generated by Django 2.0.3 on 2021-07-21 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0082_auto_20210720_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed_wf',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wf_count',
        ),
    ]
