# Generated by Django 2.0.3 on 2021-07-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0083_auto_20210721_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
