# Generated by Django 2.0.3 on 2021-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0084_auto_20210729_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='problems',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
