# Generated by Django 2.0.3 on 2021-07-29 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0085_auto_20210729_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
