# Generated by Django 2.0.3 on 2021-08-09 13:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_auto_20210729_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='root_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.RootCause', verbose_name='Kök sebep'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='solution',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Çözüm'),
        ),
    ]
